# Generated by Django 2.0 on 2017-12-03 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('nome', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=14, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('titulo', models.CharField(max_length=50)),
                ('numpag', models.CharField(max_length=50)),
                ('ano', models.CharField(max_length=8)),
                ('codigo', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('editora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Editora')),
            ],
        ),
    ]
